apiVersion: apps/v1
kind: Deployment # ReplicaSet
metadata:
    name: frontend
    namespace: expense 
    labels: # these are replicaset labels
        app: frontend 
        tier: web
        project: expense 
       
spec:
   replicas: 2
   selector:
      # these are used to select the pod to create replicas
      matchLabels:
           app: frontend 
           tier: web 
           project: expense 
   template: # this is the pod defination 
      metadata:
         labels:
              app: frontend
              tier: web
              project: expense 
      spec:         
        containers:
        -  name: frontend
           image: vvram143/frontend:v1
---
apiVersion: v1
kind: Service
metadata:
    name: frontend
    namespace: expense
spec:
    type: LoadBalancer
    selector:
         app: frontend 
         tier: web 
         project: expense 
    ports:
    - name: nginx-svc-port 
      protocol: TCP 
      port: 80 # service port
      targetPort: 80 # container port