apiVersion: v1
kind: pod
metadata:
    name: multi-container
spec:
   containers:
      -  name: nginx1
         image: nginx 
      -  name : almalinux
         image: almalinux:9
         commonad: ["sleep","1000"]  