apiVersion: v1
kind: Pod
metadata:
    name: annotations  
    annotations:
        imageregistery: "https://hub.docker.com" 
        buildURL: "https://jenkins.vvram143.com"
spec:
  containers:
  -  name: nginx
     image: nginx    