apiVersion: v1
kind: Pod
metadata:
    name: limits
spec:    
    containers:
    -  name: nginx
       image: nginx
       resource:
          limits:
            cpu: 120m
            memory: 100mi           