apiVersion: v1
kind: Pod
metadata:
    name: limits
spec:    
    containers:
    -  name: nginx
       image: nginx
       resources:
       # soft limit
          requests:
              cpu: "100m"
              memory: "68Mi"
       # hard limit       
          limits:
            cpu: "120m"
            memory: "100Mi"           
