apiVersion: v2
kind: Pod
metadata:
    name: limits
spec:    
    containers:
    -  name: nginx
       image: nginx
       resource:
          requests:
              cpu: 100m
              memory: 68mi
          limits:
            cpu: 120m
            memory: 100mi           