
apiVersion: apps/v1
kind: Deployment # ReplicaSet
metadata:
    name: nginx
    labels: # these are replicaset labels
        project: expense 
        module: frontend 
        environment: dev
spec:
   replicas: 3
   selector:
      # these are used to select the pod to create replicas
      matchLabels:
         project: expense 
         module: frontend 
         environment: dev
   template: # this is the pod defination 
      metadata:
         labels:
            project: expense 
            module: frontend 
            environment: dev 
      spec:         
        containers:
        -  name: nginx
           image: nginx:stable-perl
---
apiVersion: v1
kind: Service
metadata:
    name: nginx
spec:
    selector:
       project: expense 
       module: frontend
       environment: dev
    ports:
    - name: nginx-svc-port 
      protocol: TCP 
      port: 80 # service port
      targetPort: 80 # container port
  